version: "3.9"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
     - wordpress:/var/www/wordpress
    env_file: .env
    restart: always
    ports:
      - "443:443"
    networks:
      - network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
     - wordpress:/var/www/wordpress
    env_file: .env
    restart: always
    expose:
      - 9000
    networks:
      - network

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
     - mariadb:/var/lib/mysql
    env_file: .env
    restart: always
    expose:
     - 3306 
    networks: 
     - network


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/vagrant/data/wordpress/'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/vagrant/data/mariadb/'
   
networks:
  network:
    driver: bridge
